version: '3.8'
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test-tt-1
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./test-tt-1.sql:/docker-entrypoint-initdb.d/test-tt-1.sql
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: test-tt-1
      DB_USERNAME: root
      DB_PASSWORD: ""
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app/web
      - ./.env:/app/.env
volumes:
  db_data:
