name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:11
        env:
          MYSQL_DATABASE: test-tt-1
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_ROOT_PASSWORD: ""
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test-tt-1
      DB_USERNAME: root
      DB_PASSWORD: ""
      REDIS_ADDR: 127.0.0.1:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: go mod download

      - name: Wait for MariaDB
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -uroot --silent; then
              echo "MariaDB is up!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 2
          done

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t my_project-app .
